import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell, Section } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { pageHead } from "@/lib/head";
import { insertRow, selectRows } from "@/lib/supabase-data";

type Mentor = { id: string; nickname: string };
type House = { id: string; name: string };
export const Route = createFileRoute("/projects/create")({ head: () => pageHead("สร้างโปรเจ็ค", "สร้างข้อมูลใน Supabase"), component: CreateProject });
function CreateProject() { const navigate = useNavigate(); const [mentors, setMentors] = useState<Mentor[]>([]); const [houses, setHouses] = useState<House[]>([]); const [name, setName] = useState(""); const [type, setType] = useState(""); const [ownerType, setOwnerType] = useState<"mentor" | "house">("mentor"); const [ownerId, setOwnerId] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); useEffect(() => { Promise.all([selectRows<Mentor>("mentor_profiles", "id,nickname"), selectRows<House>("houses", "id,name")]).then(([m,h]) => { setMentors(m); setHouses(h); }).catch((e) => setError(e instanceof Error ? e.message : "โหลดข้อมูลอ้างอิงไม่สำเร็จ")); }, []); const submit = async (e: FormEvent) => { e.preventDefault(); if (!ownerId) return setError("กรุณาเลือกเจ้าของโปรเจ็ค"); setSaving(true); setError(null); try { const project = await insertRow<{ id: string }>("projects", { name, type: type || null, owner_type: ownerType, mentor_id: ownerType === "mentor" ? ownerId : null, house_id: ownerType === "house" ? ownerId : null }); await navigate({ to: "/projects" }); } catch (err) { setError(err instanceof Error ? err.message : "สร้างโปรเจ็คไม่สำเร็จ"); } finally { setSaving(false); } }; const owners = ownerType === "mentor" ? mentors : houses; return <AppShell title="สร้างโปรเจ็ค" description="บันทึกข้อมูลลง Supabase"><Section><form className="grid max-w-xl gap-4" onSubmit={submit}><div><Label>ชื่อโปรเจ็ค</Label><Input value={name} onChange={(e) => setName(e.target.value)} required /></div><div><Label>ประเภท</Label><Input value={type} onChange={(e) => setType(e.target.value)} /></div><div><Label>ประเภทเจ้าของ</Label><Select value={ownerType} onValueChange={(v) => { setOwnerType(v as "mentor" | "house"); setOwnerId(""); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="mentor">พี่เลี้ยง</SelectItem><SelectItem value="house">บ้าน</SelectItem></SelectContent></Select></div><div><Label>เจ้าของ</Label><Select value={ownerId} onValueChange={setOwnerId}><SelectTrigger><SelectValue placeholder="เลือกเจ้าของ" /></SelectTrigger><SelectContent>{owners.map((owner) => <SelectItem key={owner.id} value={owner.id}>{ownerType === "mentor" ? (owner as Mentor).nickname : (owner as House).name}</SelectItem>)}</SelectContent></Select></div>{error && <p className="text-sm text-destructive">{error}</p>}<Button disabled={saving}>{saving ? "กำลังบันทึก..." : "สร้างโปรเจ็ค"}</Button></form></Section></AppShell>; }
