import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell, Section } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { pageHead } from "@/lib/head";
import { insertRow, selectRows, updateRows } from "@/lib/supabase-data";
import { useRole } from "@/lib/role-context";
type Preference={user_id:string;in_app_enabled:boolean;email_enabled:boolean;discord_enabled:boolean};
export const Route=createFileRoute("/notifications/settings")({head:()=>pageHead("ตั้งค่าการแจ้งเตือน","บันทึกการตั้งค่าใน Supabase"),component:NotificationSettings});
function NotificationSettings(){const{user}=useRole();const[p,setP]=useState<Preference>({user_id:"",in_app_enabled:true,email_enabled:false,discord_enabled:false});const[message,setMessage]=useState("");useEffect(()=>{if(!user)return;selectRows<Preference>("notification_preferences","user_id,in_app_enabled,email_enabled,discord_enabled",`user_id=eq.${user.id}`).then(rows=>setP(rows[0]??{...p,user_id:user.id})).catch(e=>setMessage(e.message));},[user]);const save=async()=>{if(!user)return;setMessage("");try{const v={in_app_enabled:p.in_app_enabled,email_enabled:p.email_enabled,discord_enabled:p.discord_enabled};const existing=await selectRows<Preference>("notification_preferences","user_id",`user_id=eq.${user.id}`);if(existing.length)await updateRows("notification_preferences",`user_id=eq.${user.id}`,v);else await insertRow("notification_preferences",{user_id:user.id,...v});setMessage("บันทึกการตั้งค่าแล้ว");}catch(e){setMessage(e instanceof Error?e.message:"บันทึกไม่สำเร็จ");}};const rows:[[keyof Preference,string]]=[["in_app_enabled","แจ้งเตือนในระบบ"],["email_enabled","อีเมล"],["discord_enabled","Discord"]];return <AppShell title="ตั้งค่าการแจ้งเตือน" description="เลือกช่องทางรับการแจ้งเตือนของคุณ"><Section title="ช่องทาง"><div className="space-y-3">{rows.map(([key,label])=><label key={key} className="flex items-center justify-between rounded-lg border p-4"><span className="font-medium">{label}</span><Switch checked={Boolean(p[key])} onCheckedChange={checked=>setP(current=>({...current,[key]:checked}))}/></label>)}</div><div className="mt-4 flex items-center gap-3"><Button onClick={()=>void save()}>บันทึก</Button>{message&&<p className="text-sm text-muted-foreground">{message}</p>}</div></Section></AppShell>}
