import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell, Section } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { pageHead } from "@/lib/head";
import { insertRow, selectRows } from "@/lib/supabase-data";
import { useRole } from "@/lib/role-context";

type Project = { id: string; name: string }; type Trainee = { id: string; nickname: string };
export const Route = createFileRoute("/tasks/create")({ head: () => pageHead("มอบหมายงาน", "สร้างงานใน Supabase"), component: CreateTask });
function CreateTask() { const navigate = useNavigate(); const { user } = useRole(); const [projects, setProjects] = useState<Project[]>([]); const [trainees, setTrainees] = useState<Trainee[]>([]); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [projectId, setProjectId] = useState(""); const [traineeId, setTraineeId] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); useEffect(() => { Promise.all([selectRows<Project>("projects", "id,name"), selectRows<Trainee>("trainee_profiles", "id,nickname")]).then(([p,t]) => { setProjects(p); setTrainees(t); }).catch((e) => setError(e instanceof Error ? e.message : "โหลดข้อมูลอ้างอิงไม่สำเร็จ")); }, []); const submit = async (e: FormEvent) => { e.preventDefault(); if (!user || !projectId || !traineeId) return setError("กรุณาเลือกโปรเจ็คและเทรนนี่"); setSaving(true); setError(null); try { const task = await insertRow<{ id: string }>("tasks", { title, description: description || null, project_id: projectId, assigner_id: user.id, assign_type: "individual" }); await insertRow("task_assignments", { task_id: task.id, trainee_id: traineeId }); await navigate({ to: "/" }); } catch (err) { setError(err instanceof Error ? err.message : "มอบหมายงานไม่สำเร็จ"); } finally { setSaving(false); } }; return <AppShell title="มอบหมายงาน" description="สร้างงานและมอบหมายให้เทรนนี่ผ่าน Supabase"><Section><form className="grid max-w-xl gap-4" onSubmit={submit}><div><Label>ชื่องาน</Label><Input value={title} onChange={(e) => setTitle(e.target.value)} required /></div><div><Label>รายละเอียด</Label><Textarea value={description} onChange={(e) => setDescription(e.target.value)} /></div><div><Label>โปรเจ็ค</Label><Select value={projectId} onValueChange={setProjectId}><SelectTrigger><SelectValue placeholder="เลือกโปรเจ็ค" /></SelectTrigger><SelectContent>{projects.map((p) => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><div><Label>เทรนนี่</Label><Select value={traineeId} onValueChange={setTraineeId}><SelectTrigger><SelectValue placeholder="เลือกเทรนนี่" /></SelectTrigger><SelectContent>{trainees.map((t) => <SelectItem key={t.id} value={t.id}>{t.nickname}</SelectItem>)}</SelectContent></Select></div>{error && <p className="text-sm text-destructive">{error}</p>}<Button disabled={saving}>{saving ? "กำลังบันทึก..." : "มอบหมายงาน"}</Button></form></Section></AppShell>; }
