/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataStatusRouteImport } from './routes/data-status'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StandupRouteImport } from './routes/standup'
import { Route as AdminMasterDataRouteImport } from './routes/admin/master-data'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as AppointmentsAppointmentIdRouteImport } from './routes/appointments/$appointmentId'
import { Route as AppointmentsCreateRouteImport } from './routes/appointments/create'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'
import { Route as DocumentsUploadRouteImport } from './routes/documents/upload'
import { Route as ExtensionsIndexRouteImport } from './routes/extensions/index'
import { Route as ExtensionsRequestRouteImport } from './routes/extensions/request'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as IssuesReportRouteImport } from './routes/issues/report'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as KnowledgeArticleIdRouteImport } from './routes/knowledge/$articleId'
import { Route as KnowledgeApprovalsRouteImport } from './routes/knowledge/approvals'
import { Route as KnowledgeCreateRouteImport } from './routes/knowledge/create'
import { Route as LeavesIndexRouteImport } from './routes/leaves/index'
import { Route as LeavesRequestRouteImport } from './routes/leaves/request'
import { Route as ManpowerIndexRouteImport } from './routes/manpower/index'
import { Route as ManpowerRequestRouteImport } from './routes/manpower/request'
import { Route as MentorsIndexRouteImport } from './routes/mentors/index'
import { Route as MentorsMentorIdRouteImport } from './routes/mentors/$mentorId'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as NotificationsSettingsRouteImport } from './routes/notifications/settings'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsCreateRouteImport } from './routes/projects/create'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as TasksBoardRouteImport } from './routes/tasks/board'
import { Route as TasksCreateRouteImport } from './routes/tasks/create'
import { Route as TasksReviewRouteImport } from './routes/tasks/review'
import { Route as TasksTeamRouteImport } from './routes/tasks/team'
import { Route as TraineesIndexRouteImport } from './routes/trainees/index'
import { Route as TraineesTraineeIdRouteImport } from './routes/trainees/$traineeId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdDiagramRouteImport } from './routes/projects/$projectId/diagram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStatusRoute = DataStatusRouteImport.update({
  id: '/data-status',
  path: '/data-status',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StandupRoute = StandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterDataRoute = AdminMasterDataRouteImport.update({
  id: '/admin/master-data',
  path: '/admin/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsAppointmentIdRoute =
  AppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentsCreateRoute = AppointmentsCreateRouteImport.update({
  id: '/appointments/create',
  path: '/appointments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsUploadRoute = DocumentsUploadRouteImport.update({
  id: '/documents/upload',
  path: '/documents/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsIndexRoute = ExtensionsIndexRouteImport.update({
  id: '/extensions/',
  path: '/extensions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRequestRoute = ExtensionsRequestRouteImport.update({
  id: '/extensions/request',
  path: '/extensions/request',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesReportRoute = IssuesReportRouteImport.update({
  id: '/issues/report',
  path: '/issues/report',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeArticleIdRoute = KnowledgeArticleIdRouteImport.update({
  id: '/knowledge/$articleId',
  path: '/knowledge/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeApprovalsRoute = KnowledgeApprovalsRouteImport.update({
  id: '/knowledge/approvals',
  path: '/knowledge/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCreateRoute = KnowledgeCreateRouteImport.update({
  id: '/knowledge/create',
  path: '/knowledge/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesIndexRoute = LeavesIndexRouteImport.update({
  id: '/leaves/',
  path: '/leaves/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRequestRoute = LeavesRequestRouteImport.update({
  id: '/leaves/request',
  path: '/leaves/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ManpowerIndexRoute = ManpowerIndexRouteImport.update({
  id: '/manpower/',
  path: '/manpower/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManpowerRequestRoute = ManpowerRequestRouteImport.update({
  id: '/manpower/request',
  path: '/manpower/request',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIndexRoute = MentorsIndexRouteImport.update({
  id: '/mentors/',
  path: '/mentors/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsMentorIdRoute = MentorsMentorIdRouteImport.update({
  id: '/mentors/$mentorId',
  path: '/mentors/$mentorId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSettingsRoute = NotificationsSettingsRouteImport.update({
  id: '/notifications/settings',
  path: '/notifications/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksBoardRoute = TasksBoardRouteImport.update({
  id: '/tasks/board',
  path: '/tasks/board',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCreateRoute = TasksCreateRouteImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksReviewRoute = TasksReviewRouteImport.update({
  id: '/tasks/review',
  path: '/tasks/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTeamRoute = TasksTeamRouteImport.update({
  id: '/tasks/team',
  path: '/tasks/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineesIndexRoute = TraineesIndexRouteImport.update({
  id: '/trainees/',
  path: '/trainees/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineesTraineeIdRoute = TraineesTraineeIdRouteImport.update({
  id: '/trainees/$traineeId',
  path: '/trainees/$traineeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdDiagramRoute =
  ProjectsProjectIdDiagramRouteImport.update({
    id: '/projects/$projectId/diagram',
    path: '/projects/$projectId/diagram',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-status': typeof DataStatusRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/standup': typeof StandupRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/upload': typeof DocumentsUploadRoute
  '/extensions/request': typeof ExtensionsRequestRoute
  '/issues/report': typeof IssuesReportRoute
  '/knowledge/$articleId': typeof KnowledgeArticleIdRoute
  '/knowledge/approvals': typeof KnowledgeApprovalsRoute
  '/knowledge/create': typeof KnowledgeCreateRoute
  '/leaves/request': typeof LeavesRequestRoute
  '/manpower/request': typeof ManpowerRequestRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/board': typeof TasksBoardRoute
  '/tasks/create': typeof TasksCreateRoute
  '/tasks/review': typeof TasksReviewRoute
  '/tasks/team': typeof TasksTeamRoute
  '/trainees/$traineeId': typeof TraineesTraineeIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/leaves/': typeof LeavesIndexRoute
  '/manpower/': typeof ManpowerIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/trainees/': typeof TraineesIndexRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-status': typeof DataStatusRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/standup': typeof StandupRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/upload': typeof DocumentsUploadRoute
  '/extensions/request': typeof ExtensionsRequestRoute
  '/issues/report': typeof IssuesReportRoute
  '/knowledge/$articleId': typeof KnowledgeArticleIdRoute
  '/knowledge/approvals': typeof KnowledgeApprovalsRoute
  '/knowledge/create': typeof KnowledgeCreateRoute
  '/leaves/request': typeof LeavesRequestRoute
  '/manpower/request': typeof ManpowerRequestRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/board': typeof TasksBoardRoute
  '/tasks/create': typeof TasksCreateRoute
  '/tasks/review': typeof TasksReviewRoute
  '/tasks/team': typeof TasksTeamRoute
  '/trainees/$traineeId': typeof TraineesTraineeIdRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/extensions': typeof ExtensionsIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/leaves': typeof LeavesIndexRoute
  '/manpower': typeof ManpowerIndexRoute
  '/mentors': typeof MentorsIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/trainees': typeof TraineesIndexRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-status': typeof DataStatusRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/standup': typeof StandupRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/upload': typeof DocumentsUploadRoute
  '/extensions/request': typeof ExtensionsRequestRoute
  '/issues/report': typeof IssuesReportRoute
  '/knowledge/$articleId': typeof KnowledgeArticleIdRoute
  '/knowledge/approvals': typeof KnowledgeApprovalsRoute
  '/knowledge/create': typeof KnowledgeCreateRoute
  '/leaves/request': typeof LeavesRequestRoute
  '/manpower/request': typeof ManpowerRequestRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/board': typeof TasksBoardRoute
  '/tasks/create': typeof TasksCreateRoute
  '/tasks/review': typeof TasksReviewRoute
  '/tasks/team': typeof TasksTeamRoute
  '/trainees/$traineeId': typeof TraineesTraineeIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/leaves/': typeof LeavesIndexRoute
  '/manpower/': typeof ManpowerIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/trainees/': typeof TraineesIndexRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/data-status'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/search'
    | '/standup'
    | '/admin/master-data'
    | '/admin/users'
    | '/appointments/$appointmentId'
    | '/appointments/create'
    | '/documents/$documentId'
    | '/documents/upload'
    | '/extensions/request'
    | '/issues/report'
    | '/knowledge/$articleId'
    | '/knowledge/approvals'
    | '/knowledge/create'
    | '/leaves/request'
    | '/manpower/request'
    | '/mentors/$mentorId'
    | '/notifications/settings'
    | '/projects/create'
    | '/tasks/$taskId'
    | '/tasks/board'
    | '/tasks/create'
    | '/tasks/review'
    | '/tasks/team'
    | '/trainees/$traineeId'
    | '/appointments/'
    | '/documents/'
    | '/extensions/'
    | '/issues/'
    | '/knowledge/'
    | '/leaves/'
    | '/manpower/'
    | '/mentors/'
    | '/notifications/'
    | '/projects/'
    | '/trainees/'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/data-status'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/search'
    | '/standup'
    | '/admin/master-data'
    | '/admin/users'
    | '/appointments/$appointmentId'
    | '/appointments/create'
    | '/documents/$documentId'
    | '/documents/upload'
    | '/extensions/request'
    | '/issues/report'
    | '/knowledge/$articleId'
    | '/knowledge/approvals'
    | '/knowledge/create'
    | '/leaves/request'
    | '/manpower/request'
    | '/mentors/$mentorId'
    | '/notifications/settings'
    | '/projects/create'
    | '/tasks/$taskId'
    | '/tasks/board'
    | '/tasks/create'
    | '/tasks/review'
    | '/tasks/team'
    | '/trainees/$traineeId'
    | '/appointments'
    | '/documents'
    | '/extensions'
    | '/issues'
    | '/knowledge'
    | '/leaves'
    | '/manpower'
    | '/mentors'
    | '/notifications'
    | '/projects'
    | '/trainees'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/data-status'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/search'
    | '/standup'
    | '/admin/master-data'
    | '/admin/users'
    | '/appointments/$appointmentId'
    | '/appointments/create'
    | '/documents/$documentId'
    | '/documents/upload'
    | '/extensions/request'
    | '/issues/report'
    | '/knowledge/$articleId'
    | '/knowledge/approvals'
    | '/knowledge/create'
    | '/leaves/request'
    | '/manpower/request'
    | '/mentors/$mentorId'
    | '/notifications/settings'
    | '/projects/create'
    | '/tasks/$taskId'
    | '/tasks/board'
    | '/tasks/create'
    | '/tasks/review'
    | '/tasks/team'
    | '/trainees/$traineeId'
    | '/appointments/'
    | '/documents/'
    | '/extensions/'
    | '/issues/'
    | '/knowledge/'
    | '/leaves/'
    | '/manpower/'
    | '/mentors/'
    | '/notifications/'
    | '/projects/'
    | '/trainees/'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DataStatusRoute: typeof DataStatusRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  StandupRoute: typeof StandupRoute
  AdminMasterDataRoute: typeof AdminMasterDataRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AppointmentsAppointmentIdRoute: typeof AppointmentsAppointmentIdRoute
  AppointmentsCreateRoute: typeof AppointmentsCreateRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  DocumentsUploadRoute: typeof DocumentsUploadRoute
  ExtensionsRequestRoute: typeof ExtensionsRequestRoute
  IssuesReportRoute: typeof IssuesReportRoute
  KnowledgeArticleIdRoute: typeof KnowledgeArticleIdRoute
  KnowledgeApprovalsRoute: typeof KnowledgeApprovalsRoute
  KnowledgeCreateRoute: typeof KnowledgeCreateRoute
  LeavesRequestRoute: typeof LeavesRequestRoute
  ManpowerRequestRoute: typeof ManpowerRequestRoute
  MentorsMentorIdRoute: typeof MentorsMentorIdRoute
  NotificationsSettingsRoute: typeof NotificationsSettingsRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksBoardRoute: typeof TasksBoardRoute
  TasksCreateRoute: typeof TasksCreateRoute
  TasksReviewRoute: typeof TasksReviewRoute
  TasksTeamRoute: typeof TasksTeamRoute
  TraineesTraineeIdRoute: typeof TraineesTraineeIdRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  ExtensionsIndexRoute: typeof ExtensionsIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  LeavesIndexRoute: typeof LeavesIndexRoute
  ManpowerIndexRoute: typeof ManpowerIndexRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TraineesIndexRoute: typeof TraineesIndexRoute
  ProjectsProjectIdDiagramRoute: typeof ProjectsProjectIdDiagramRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-status': {
      id: '/data-status'
      path: '/data-status'
      fullPath: '/data-status'
      preLoaderRoute: typeof DataStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standup': {
      id: '/standup'
      path: '/standup'
      fullPath: '/standup'
      preLoaderRoute: typeof StandupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/master-data': {
      id: '/admin/master-data'
      path: '/admin/master-data'
      fullPath: '/admin/master-data'
      preLoaderRoute: typeof AdminMasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$appointmentId': {
      id: '/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AppointmentsAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/create': {
      id: '/appointments/create'
      path: '/appointments/create'
      fullPath: '/appointments/create'
      preLoaderRoute: typeof AppointmentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/upload': {
      id: '/documents/upload'
      path: '/documents/upload'
      fullPath: '/documents/upload'
      preLoaderRoute: typeof DocumentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/': {
      id: '/extensions/'
      path: '/extensions'
      fullPath: '/extensions/'
      preLoaderRoute: typeof ExtensionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/request': {
      id: '/extensions/request'
      path: '/extensions/request'
      fullPath: '/extensions/request'
      preLoaderRoute: typeof ExtensionsRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/report': {
      id: '/issues/report'
      path: '/issues/report'
      fullPath: '/issues/report'
      preLoaderRoute: typeof IssuesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$articleId': {
      id: '/knowledge/$articleId'
      path: '/knowledge/$articleId'
      fullPath: '/knowledge/$articleId'
      preLoaderRoute: typeof KnowledgeArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/approvals': {
      id: '/knowledge/approvals'
      path: '/knowledge/approvals'
      fullPath: '/knowledge/approvals'
      preLoaderRoute: typeof KnowledgeApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/create': {
      id: '/knowledge/create'
      path: '/knowledge/create'
      fullPath: '/knowledge/create'
      preLoaderRoute: typeof KnowledgeCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves/': {
      id: '/leaves/'
      path: '/leaves'
      fullPath: '/leaves/'
      preLoaderRoute: typeof LeavesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves/request': {
      id: '/leaves/request'
      path: '/leaves/request'
      fullPath: '/leaves/request'
      preLoaderRoute: typeof LeavesRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manpower/': {
      id: '/manpower/'
      path: '/manpower'
      fullPath: '/manpower/'
      preLoaderRoute: typeof ManpowerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manpower/request': {
      id: '/manpower/request'
      path: '/manpower/request'
      fullPath: '/manpower/request'
      preLoaderRoute: typeof ManpowerRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/mentors'
      fullPath: '/mentors/'
      preLoaderRoute: typeof MentorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/$mentorId': {
      id: '/mentors/$mentorId'
      path: '/mentors/$mentorId'
      fullPath: '/mentors/$mentorId'
      preLoaderRoute: typeof MentorsMentorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/settings': {
      id: '/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof NotificationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/board': {
      id: '/tasks/board'
      path: '/tasks/board'
      fullPath: '/tasks/board'
      preLoaderRoute: typeof TasksBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/review': {
      id: '/tasks/review'
      path: '/tasks/review'
      fullPath: '/tasks/review'
      preLoaderRoute: typeof TasksReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/team': {
      id: '/tasks/team'
      path: '/tasks/team'
      fullPath: '/tasks/team'
      preLoaderRoute: typeof TasksTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainees/': {
      id: '/trainees/'
      path: '/trainees'
      fullPath: '/trainees/'
      preLoaderRoute: typeof TraineesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainees/$traineeId': {
      id: '/trainees/$traineeId'
      path: '/trainees/$traineeId'
      fullPath: '/trainees/$traineeId'
      preLoaderRoute: typeof TraineesTraineeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/diagram': {
      id: '/projects/$projectId/diagram'
      path: '/projects/$projectId/diagram'
      fullPath: '/projects/$projectId/diagram'
      preLoaderRoute: typeof ProjectsProjectIdDiagramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DataStatusRoute: DataStatusRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  StandupRoute: StandupRoute,
  AdminMasterDataRoute: AdminMasterDataRoute,
  AdminUsersRoute: AdminUsersRoute,
  AppointmentsAppointmentIdRoute: AppointmentsAppointmentIdRoute,
  AppointmentsCreateRoute: AppointmentsCreateRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  DocumentsUploadRoute: DocumentsUploadRoute,
  ExtensionsRequestRoute: ExtensionsRequestRoute,
  IssuesReportRoute: IssuesReportRoute,
  KnowledgeArticleIdRoute: KnowledgeArticleIdRoute,
  KnowledgeApprovalsRoute: KnowledgeApprovalsRoute,
  KnowledgeCreateRoute: KnowledgeCreateRoute,
  LeavesRequestRoute: LeavesRequestRoute,
  ManpowerRequestRoute: ManpowerRequestRoute,
  MentorsMentorIdRoute: MentorsMentorIdRoute,
  NotificationsSettingsRoute: NotificationsSettingsRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksBoardRoute: TasksBoardRoute,
  TasksCreateRoute: TasksCreateRoute,
  TasksReviewRoute: TasksReviewRoute,
  TasksTeamRoute: TasksTeamRoute,
  TraineesTraineeIdRoute: TraineesTraineeIdRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  ExtensionsIndexRoute: ExtensionsIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  LeavesIndexRoute: LeavesIndexRoute,
  ManpowerIndexRoute: ManpowerIndexRoute,
  MentorsIndexRoute: MentorsIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TraineesIndexRoute: TraineesIndexRoute,
  ProjectsProjectIdDiagramRoute: ProjectsProjectIdDiagramRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
